
# encoding: utf-8

# *** GENERATED BY `setup.py antlr`, DO NOT EDIT BY HAND ***
#
# Generated from ../LaTeX.g4, derived from latex2sympy
#     latex2sympy is licensed under the MIT license
#     https://github.com/augustt198/latex2sympy/blob/master/LICENSE.txt
#
# Generated with antlr4
#    antlr4 is licensed under the BSD-3-Clause License
#    https://github.com/antlr/antlr4/blob/master/LICENSE.txt
from __future__ import print_function
from antlr4 import *
from io import StringIO
import sys



def serializedATN():
    with StringIO() as buf:
        buf.write(u"\3\u608b\ua72a\u8133\ub9ed\u417c\u3be7\u7786\u5964\2")
        buf.write(u"D\u023b\b\1\4\2\t\2\4\3\t\3\4\4\t\4\4\5\t\5\4\6\t\6\4")
        buf.write(u"\7\t\7\4\b\t\b\4\t\t\t\4\n\t\n\4\13\t\13\4\f\t\f\4\r")
        buf.write(u"\t\r\4\16\t\16\4\17\t\17\4\20\t\20\4\21\t\21\4\22\t\22")
        buf.write(u"\4\23\t\23\4\24\t\24\4\25\t\25\4\26\t\26\4\27\t\27\4")
        buf.write(u"\30\t\30\4\31\t\31\4\32\t\32\4\33\t\33\4\34\t\34\4\35")
        buf.write(u"\t\35\4\36\t\36\4\37\t\37\4 \t \4!\t!\4\"\t\"\4#\t#\4")
        buf.write(u"$\t$\4%\t%\4&\t&\4\'\t\'\4(\t(\4)\t)\4*\t*\4+\t+\4,\t")
        buf.write(u",\4-\t-\4.\t.\4/\t/\4\60\t\60\4\61\t\61\4\62\t\62\4\63")
        buf.write(u"\t\63\4\64\t\64\4\65\t\65\4\66\t\66\4\67\t\67\48\t8\4")
        buf.write(u"9\t9\4:\t:\4;\t;\4<\t<\4=\t=\4>\t>\4?\t?\4@\t@\4A\tA")
        buf.write(u"\4B\tB\4C\tC\4D\tD\4E\tE\3\2\3\2\3\3\6\3\u008f\n\3\r")
        buf.write(u"\3\16\3\u0090\3\3\3\3\3\4\3\4\3\5\3\5\3\6\3\6\3\7\3\7")
        buf.write(u"\3\b\3\b\3\t\3\t\3\n\3\n\3\13\3\13\3\f\3\f\3\r\3\r\3")
        buf.write(u"\16\3\16\3\17\3\17\3\17\3\17\3\17\3\20\3\20\3\20\3\20")
        buf.write(u"\3\20\3\20\3\20\3\20\3\20\3\20\3\20\3\20\3\20\3\20\3")
        buf.write(u"\20\3\20\3\20\3\20\3\20\3\20\3\20\3\20\3\20\3\20\3\20")
        buf.write(u"\3\20\3\20\3\20\3\20\3\20\3\20\3\20\3\20\3\20\3\20\3")
        buf.write(u"\20\3\20\3\20\3\20\3\20\3\20\3\20\3\20\3\20\3\20\3\20")
        buf.write(u"\3\20\3\20\3\20\3\20\3\20\3\20\3\20\3\20\3\20\5\20\u00e7")
        buf.write(u"\n\20\3\21\3\21\3\21\3\21\3\21\3\22\3\22\3\22\3\22\3")
        buf.write(u"\22\3\23\3\23\3\23\3\23\3\23\3\23\3\24\3\24\3\24\3\24")
        buf.write(u"\3\24\3\25\3\25\3\25\3\25\3\26\3\26\3\26\3\26\3\26\3")
        buf.write(u"\27\3\27\3\27\3\27\3\27\3\30\3\30\3\30\3\30\3\30\3\31")
        buf.write(u"\3\31\3\31\3\31\3\31\3\32\3\32\3\32\3\32\3\32\3\33\3")
        buf.write(u"\33\3\33\3\33\3\33\3\34\3\34\3\34\3\34\3\34\3\34\3\34")
        buf.write(u"\3\34\3\35\3\35\3\35\3\35\3\35\3\35\3\35\3\35\3\36\3")
        buf.write(u"\36\3\36\3\36\3\36\3\36\3\36\3\36\3\37\3\37\3\37\3\37")
        buf.write(u"\3\37\3\37\3\37\3\37\3 \3 \3 \3 \3 \3 \3 \3 \3!\3!\3")
        buf.write(u"!\3!\3!\3!\3!\3!\3\"\3\"\3\"\3\"\3\"\3\"\3#\3#\3#\3#")
        buf.write(u"\3#\3#\3$\3$\3$\3$\3$\3$\3%\3%\3%\3%\3%\3%\3&\3&\3&\3")
        buf.write(u"&\3&\3&\3\'\3\'\3\'\3\'\3\'\3\'\3(\3(\3(\3(\3(\3(\3(")
        buf.write(u"\3(\3)\3)\3)\3)\3)\3)\3)\3)\3*\3*\3*\3*\3*\3*\3*\3*\3")
        buf.write(u"+\3+\3+\3+\3+\3+\3+\3+\3,\3,\3,\3,\3,\3,\3,\3,\3-\3-")
        buf.write(u"\3-\3-\3-\3-\3-\3-\3.\3.\3.\3.\3.\3.\3/\3/\3/\3/\3/\3")
        buf.write(u"/\3/\3\60\3\60\3\60\3\60\3\60\3\60\3\61\3\61\3\61\3\61")
        buf.write(u"\3\61\3\62\3\62\3\62\3\62\3\62\3\62\3\63\3\63\3\63\3")
        buf.write(u"\63\3\63\3\63\3\63\3\64\3\64\3\64\3\64\3\64\3\64\3\64")
        buf.write(u"\3\64\3\65\3\65\3\65\3\65\3\65\3\65\3\65\3\65\3\66\3")
        buf.write(u"\66\3\66\3\66\3\66\3\66\3\66\3\66\3\67\3\67\38\38\39")
        buf.write(u"\39\3:\3:\3;\3;\7;\u01eb\n;\f;\16;\u01ee\13;\3;\3;\3")
        buf.write(u";\6;\u01f3\n;\r;\16;\u01f4\5;\u01f7\n;\3<\3<\3=\3=\3")
        buf.write(u">\6>\u01fe\n>\r>\16>\u01ff\3>\3>\3>\3>\3>\7>\u0207\n")
        buf.write(u">\f>\16>\u020a\13>\3>\7>\u020d\n>\f>\16>\u0210\13>\3")
        buf.write(u">\3>\3>\3>\3>\7>\u0217\n>\f>\16>\u021a\13>\3>\3>\6>\u021e")
        buf.write(u"\n>\r>\16>\u021f\5>\u0222\n>\3?\3?\3@\3@\3A\3A\3A\3A")
        buf.write(u"\3A\3B\3B\3C\3C\3C\3C\3C\3D\3D\3E\3E\6E\u0238\nE\rE\16")
        buf.write(u"E\u0239\3\u01ec\2F\3\3\5\4\7\5\t\6\13\7\r\b\17\t\21\n")
        buf.write(u"\23\13\25\f\27\r\31\16\33\17\35\20\37\21!\22#\23%\24")
        buf.write(u"\'\25)\26+\27-\30/\31\61\32\63\33\65\34\67\359\36;\37")
        buf.write(u"= ?!A\"C#E$G%I&K\'M(O)Q*S+U,W-Y.[/]\60_\61a\62c\63e\64")
        buf.write(u"g\65i\66k\67m8o9q:s\2u;w<y\2{=}>\177?\u0081@\u0083A\u0085")
        buf.write(u"B\u0087C\u0089D\3\2\5\5\2\13\f\17\17\"\"\4\2C\\c|\3\2")
        buf.write(u"\62;\2\u0247\2\3\3\2\2\2\2\5\3\2\2\2\2\7\3\2\2\2\2\t")
        buf.write(u"\3\2\2\2\2\13\3\2\2\2\2\r\3\2\2\2\2\17\3\2\2\2\2\21\3")
        buf.write(u"\2\2\2\2\23\3\2\2\2\2\25\3\2\2\2\2\27\3\2\2\2\2\31\3")
        buf.write(u"\2\2\2\2\33\3\2\2\2\2\35\3\2\2\2\2\37\3\2\2\2\2!\3\2")
        buf.write(u"\2\2\2#\3\2\2\2\2%\3\2\2\2\2\'\3\2\2\2\2)\3\2\2\2\2+")
        buf.write(u"\3\2\2\2\2-\3\2\2\2\2/\3\2\2\2\2\61\3\2\2\2\2\63\3\2")
        buf.write(u"\2\2\2\65\3\2\2\2\2\67\3\2\2\2\29\3\2\2\2\2;\3\2\2\2")
        buf.write(u"\2=\3\2\2\2\2?\3\2\2\2\2A\3\2\2\2\2C\3\2\2\2\2E\3\2\2")
        buf.write(u"\2\2G\3\2\2\2\2I\3\2\2\2\2K\3\2\2\2\2M\3\2\2\2\2O\3\2")
        buf.write(u"\2\2\2Q\3\2\2\2\2S\3\2\2\2\2U\3\2\2\2\2W\3\2\2\2\2Y\3")
        buf.write(u"\2\2\2\2[\3\2\2\2\2]\3\2\2\2\2_\3\2\2\2\2a\3\2\2\2\2")
        buf.write(u"c\3\2\2\2\2e\3\2\2\2\2g\3\2\2\2\2i\3\2\2\2\2k\3\2\2\2")
        buf.write(u"\2m\3\2\2\2\2o\3\2\2\2\2q\3\2\2\2\2u\3\2\2\2\2w\3\2\2")
        buf.write(u"\2\2{\3\2\2\2\2}\3\2\2\2\2\177\3\2\2\2\2\u0081\3\2\2")
        buf.write(u"\2\2\u0083\3\2\2\2\2\u0085\3\2\2\2\2\u0087\3\2\2\2\2")
        buf.write(u"\u0089\3\2\2\2\3\u008b\3\2\2\2\5\u008e\3\2\2\2\7\u0094")
        buf.write(u"\3\2\2\2\t\u0096\3\2\2\2\13\u0098\3\2\2\2\r\u009a\3\2")
        buf.write(u"\2\2\17\u009c\3\2\2\2\21\u009e\3\2\2\2\23\u00a0\3\2\2")
        buf.write(u"\2\25\u00a2\3\2\2\2\27\u00a4\3\2\2\2\31\u00a6\3\2\2\2")
        buf.write(u"\33\u00a8\3\2\2\2\35\u00aa\3\2\2\2\37\u00e6\3\2\2\2!")
        buf.write(u"\u00e8\3\2\2\2#\u00ed\3\2\2\2%\u00f2\3\2\2\2\'\u00f8")
        buf.write(u"\3\2\2\2)\u00fd\3\2\2\2+\u0101\3\2\2\2-\u0106\3\2\2\2")
        buf.write(u"/\u010b\3\2\2\2\61\u0110\3\2\2\2\63\u0115\3\2\2\2\65")
        buf.write(u"\u011a\3\2\2\2\67\u011f\3\2\2\29\u0127\3\2\2\2;\u012f")
        buf.write(u"\3\2\2\2=\u0137\3\2\2\2?\u013f\3\2\2\2A\u0147\3\2\2\2")
        buf.write(u"C\u014f\3\2\2\2E\u0155\3\2\2\2G\u015b\3\2\2\2I\u0161")
        buf.write(u"\3\2\2\2K\u0167\3\2\2\2M\u016d\3\2\2\2O\u0173\3\2\2\2")
        buf.write(u"Q\u017b\3\2\2\2S\u0183\3\2\2\2U\u018b\3\2\2\2W\u0193")
        buf.write(u"\3\2\2\2Y\u019b\3\2\2\2[\u01a3\3\2\2\2]\u01a9\3\2\2\2")
        buf.write(u"_\u01b0\3\2\2\2a\u01b6\3\2\2\2c\u01bb\3\2\2\2e\u01c1")
        buf.write(u"\3\2\2\2g\u01c8\3\2\2\2i\u01d0\3\2\2\2k\u01d8\3\2\2\2")
        buf.write(u"m\u01e0\3\2\2\2o\u01e2\3\2\2\2q\u01e4\3\2\2\2s\u01e6")
        buf.write(u"\3\2\2\2u\u01e8\3\2\2\2w\u01f8\3\2\2\2y\u01fa\3\2\2\2")
        buf.write(u"{\u0221\3\2\2\2}\u0223\3\2\2\2\177\u0225\3\2\2\2\u0081")
        buf.write(u"\u0227\3\2\2\2\u0083\u022c\3\2\2\2\u0085\u022e\3\2\2")
        buf.write(u"\2\u0087\u0233\3\2\2\2\u0089\u0235\3\2\2\2\u008b\u008c")
        buf.write(u"\7.\2\2\u008c\4\3\2\2\2\u008d\u008f\t\2\2\2\u008e\u008d")
        buf.write(u"\3\2\2\2\u008f\u0090\3\2\2\2\u0090\u008e\3\2\2\2\u0090")
        buf.write(u"\u0091\3\2\2\2\u0091\u0092\3\2\2\2\u0092\u0093\b\3\2")
        buf.write(u"\2\u0093\6\3\2\2\2\u0094\u0095\7-\2\2\u0095\b\3\2\2\2")
        buf.write(u"\u0096\u0097\7/\2\2\u0097\n\3\2\2\2\u0098\u0099\7,\2")
        buf.write(u"\2\u0099\f\3\2\2\2\u009a\u009b\7\61\2\2\u009b\16\3\2")
        buf.write(u"\2\2\u009c\u009d\7*\2\2\u009d\20\3\2\2\2\u009e\u009f")
        buf.write(u"\7+\2\2\u009f\22\3\2\2\2\u00a0\u00a1\7}\2\2\u00a1\24")
        buf.write(u"\3\2\2\2\u00a2\u00a3\7\177\2\2\u00a3\26\3\2\2\2\u00a4")
        buf.write(u"\u00a5\7]\2\2\u00a5\30\3\2\2\2\u00a6\u00a7\7_\2\2\u00a7")
        buf.write(u"\32\3\2\2\2\u00a8\u00a9\7~\2\2\u00a9\34\3\2\2\2\u00aa")
        buf.write(u"\u00ab\7^\2\2\u00ab\u00ac\7n\2\2\u00ac\u00ad\7k\2\2\u00ad")
        buf.write(u"\u00ae\7o\2\2\u00ae\36\3\2\2\2\u00af\u00b0\7^\2\2\u00b0")
        buf.write(u"\u00b1\7v\2\2\u00b1\u00e7\7q\2\2\u00b2\u00b3\7^\2\2\u00b3")
        buf.write(u"\u00b4\7t\2\2\u00b4\u00b5\7k\2\2\u00b5\u00b6\7i\2\2\u00b6")
        buf.write(u"\u00b7\7j\2\2\u00b7\u00b8\7v\2\2\u00b8\u00b9\7c\2\2\u00b9")
        buf.write(u"\u00ba\7t\2\2\u00ba\u00bb\7t\2\2\u00bb\u00bc\7q\2\2\u00bc")
        buf.write(u"\u00e7\7y\2\2\u00bd\u00be\7^\2\2\u00be\u00bf\7T\2\2\u00bf")
        buf.write(u"\u00c0\7k\2\2\u00c0\u00c1\7i\2\2\u00c1\u00c2\7j\2\2\u00c2")
        buf.write(u"\u00c3\7v\2\2\u00c3\u00c4\7c\2\2\u00c4\u00c5\7t\2\2\u00c5")
        buf.write(u"\u00c6\7t\2\2\u00c6\u00c7\7q\2\2\u00c7\u00e7\7y\2\2\u00c8")
        buf.write(u"\u00c9\7^\2\2\u00c9\u00ca\7n\2\2\u00ca\u00cb\7q\2\2\u00cb")
        buf.write(u"\u00cc\7p\2\2\u00cc\u00cd\7i\2\2\u00cd\u00ce\7t\2\2\u00ce")
        buf.write(u"\u00cf\7k\2\2\u00cf\u00d0\7i\2\2\u00d0\u00d1\7j\2\2\u00d1")
        buf.write(u"\u00d2\7v\2\2\u00d2\u00d3\7c\2\2\u00d3\u00d4\7t\2\2\u00d4")
        buf.write(u"\u00d5\7t\2\2\u00d5\u00d6\7q\2\2\u00d6\u00e7\7y\2\2\u00d7")
        buf.write(u"\u00d8\7^\2\2\u00d8\u00d9\7N\2\2\u00d9\u00da\7q\2\2\u00da")
        buf.write(u"\u00db\7p\2\2\u00db\u00dc\7i\2\2\u00dc\u00dd\7t\2\2\u00dd")
        buf.write(u"\u00de\7k\2\2\u00de\u00df\7i\2\2\u00df\u00e0\7j\2\2\u00e0")
        buf.write(u"\u00e1\7v\2\2\u00e1\u00e2\7c\2\2\u00e2\u00e3\7t\2\2\u00e3")
        buf.write(u"\u00e4\7t\2\2\u00e4\u00e5\7q\2\2\u00e5\u00e7\7y\2\2\u00e6")
        buf.write(u"\u00af\3\2\2\2\u00e6\u00b2\3\2\2\2\u00e6\u00bd\3\2\2")
        buf.write(u"\2\u00e6\u00c8\3\2\2\2\u00e6\u00d7\3\2\2\2\u00e7 \3\2")
        buf.write(u"\2\2\u00e8\u00e9\7^\2\2\u00e9\u00ea\7k\2\2\u00ea\u00eb")
        buf.write(u"\7p\2\2\u00eb\u00ec\7v\2\2\u00ec\"\3\2\2\2\u00ed\u00ee")
        buf.write(u"\7^\2\2\u00ee\u00ef\7u\2\2\u00ef\u00f0\7w\2\2\u00f0\u00f1")
        buf.write(u"\7o\2\2\u00f1$\3\2\2\2\u00f2\u00f3\7^\2\2\u00f3\u00f4")
        buf.write(u"\7r\2\2\u00f4\u00f5\7t\2\2\u00f5\u00f6\7q\2\2\u00f6\u00f7")
        buf.write(u"\7f\2\2\u00f7&\3\2\2\2\u00f8\u00f9\7^\2\2\u00f9\u00fa")
        buf.write(u"\7n\2\2\u00fa\u00fb\7q\2\2\u00fb\u00fc\7i\2\2\u00fc(")
        buf.write(u"\3\2\2\2\u00fd\u00fe\7^\2\2\u00fe\u00ff\7n\2\2\u00ff")
        buf.write(u"\u0100\7p\2\2\u0100*\3\2\2\2\u0101\u0102\7^\2\2\u0102")
        buf.write(u"\u0103\7u\2\2\u0103\u0104\7k\2\2\u0104\u0105\7p\2\2\u0105")
        buf.write(u",\3\2\2\2\u0106\u0107\7^\2\2\u0107\u0108\7e\2\2\u0108")
        buf.write(u"\u0109\7q\2\2\u0109\u010a\7u\2\2\u010a.\3\2\2\2\u010b")
        buf.write(u"\u010c\7^\2\2\u010c\u010d\7v\2\2\u010d\u010e\7c\2\2\u010e")
        buf.write(u"\u010f\7p\2\2\u010f\60\3\2\2\2\u0110\u0111\7^\2\2\u0111")
        buf.write(u"\u0112\7e\2\2\u0112\u0113\7u\2\2\u0113\u0114\7e\2\2\u0114")
        buf.write(u"\62\3\2\2\2\u0115\u0116\7^\2\2\u0116\u0117\7u\2\2\u0117")
        buf.write(u"\u0118\7g\2\2\u0118\u0119\7e\2\2\u0119\64\3\2\2\2\u011a")
        buf.write(u"\u011b\7^\2\2\u011b\u011c\7e\2\2\u011c\u011d\7q\2\2\u011d")
        buf.write(u"\u011e\7v\2\2\u011e\66\3\2\2\2\u011f\u0120\7^\2\2\u0120")
        buf.write(u"\u0121\7c\2\2\u0121\u0122\7t\2\2\u0122\u0123\7e\2\2\u0123")
        buf.write(u"\u0124\7u\2\2\u0124\u0125\7k\2\2\u0125\u0126\7p\2\2\u0126")
        buf.write(u"8\3\2\2\2\u0127\u0128\7^\2\2\u0128\u0129\7c\2\2\u0129")
        buf.write(u"\u012a\7t\2\2\u012a\u012b\7e\2\2\u012b\u012c\7e\2\2\u012c")
        buf.write(u"\u012d\7q\2\2\u012d\u012e\7u\2\2\u012e:\3\2\2\2\u012f")
        buf.write(u"\u0130\7^\2\2\u0130\u0131\7c\2\2\u0131\u0132\7t\2\2\u0132")
        buf.write(u"\u0133\7e\2\2\u0133\u0134\7v\2\2\u0134\u0135\7c\2\2\u0135")
        buf.write(u"\u0136\7p\2\2\u0136<\3\2\2\2\u0137\u0138\7^\2\2\u0138")
        buf.write(u"\u0139\7c\2\2\u0139\u013a\7t\2\2\u013a\u013b\7e\2\2\u013b")
        buf.write(u"\u013c\7e\2\2\u013c\u013d\7u\2\2\u013d\u013e\7e\2\2\u013e")
        buf.write(u">\3\2\2\2\u013f\u0140\7^\2\2\u0140\u0141\7c\2\2\u0141")
        buf.write(u"\u0142\7t\2\2\u0142\u0143\7e\2\2\u0143\u0144\7u\2\2\u0144")
        buf.write(u"\u0145\7g\2\2\u0145\u0146\7e\2\2\u0146@\3\2\2\2\u0147")
        buf.write(u"\u0148\7^\2\2\u0148\u0149\7c\2\2\u0149\u014a\7t\2\2\u014a")
        buf.write(u"\u014b\7e\2\2\u014b\u014c\7e\2\2\u014c\u014d\7q\2\2\u014d")
        buf.write(u"\u014e\7v\2\2\u014eB\3\2\2\2\u014f\u0150\7^\2\2\u0150")
        buf.write(u"\u0151\7u\2\2\u0151\u0152\7k\2\2\u0152\u0153\7p\2\2\u0153")
        buf.write(u"\u0154\7j\2\2\u0154D\3\2\2\2\u0155\u0156\7^\2\2\u0156")
        buf.write(u"\u0157\7e\2\2\u0157\u0158\7q\2\2\u0158\u0159\7u\2\2\u0159")
        buf.write(u"\u015a\7j\2\2\u015aF\3\2\2\2\u015b\u015c\7^\2\2\u015c")
        buf.write(u"\u015d\7v\2\2\u015d\u015e\7c\2\2\u015e\u015f\7p\2\2\u015f")
        buf.write(u"\u0160\7j\2\2\u0160H\3\2\2\2\u0161\u0162\7^\2\2\u0162")
        buf.write(u"\u0163\7e\2\2\u0163\u0164\7u\2\2\u0164\u0165\7e\2\2\u0165")
        buf.write(u"\u0166\7j\2\2\u0166J\3\2\2\2\u0167\u0168\7^\2\2\u0168")
        buf.write(u"\u0169\7u\2\2\u0169\u016a\7g\2\2\u016a\u016b\7e\2\2\u016b")
        buf.write(u"\u016c\7j\2\2\u016cL\3\2\2\2\u016d\u016e\7^\2\2\u016e")
        buf.write(u"\u016f\7e\2\2\u016f\u0170\7q\2\2\u0170\u0171\7v\2\2\u0171")
        buf.write(u"\u0172\7j\2\2\u0172N\3\2\2\2\u0173\u0174\7^\2\2\u0174")
        buf.write(u"\u0175\7c\2\2\u0175\u0176\7t\2\2\u0176\u0177\7u\2\2\u0177")
        buf.write(u"\u0178\7k\2\2\u0178\u0179\7p\2\2\u0179\u017a\7j\2\2\u017a")
        buf.write(u"P\3\2\2\2\u017b\u017c\7^\2\2\u017c\u017d\7c\2\2\u017d")
        buf.write(u"\u017e\7t\2\2\u017e\u017f\7e\2\2\u017f\u0180\7q\2\2\u0180")
        buf.write(u"\u0181\7u\2\2\u0181\u0182\7j\2\2\u0182R\3\2\2\2\u0183")
        buf.write(u"\u0184\7^\2\2\u0184\u0185\7c\2\2\u0185\u0186\7t\2\2\u0186")
        buf.write(u"\u0187\7v\2\2\u0187\u0188\7c\2\2\u0188\u0189\7p\2\2\u0189")
        buf.write(u"\u018a\7j\2\2\u018aT\3\2\2\2\u018b\u018c\7^\2\2\u018c")
        buf.write(u"\u018d\7c\2\2\u018d\u018e\7t\2\2\u018e\u018f\7e\2\2\u018f")
        buf.write(u"\u0190\7u\2\2\u0190\u0191\7e\2\2\u0191\u0192\7j\2\2\u0192")
        buf.write(u"V\3\2\2\2\u0193\u0194\7^\2\2\u0194\u0195\7c\2\2\u0195")
        buf.write(u"\u0196\7t\2\2\u0196\u0197\7u\2\2\u0197\u0198\7g\2\2\u0198")
        buf.write(u"\u0199\7e\2\2\u0199\u019a\7j\2\2\u019aX\3\2\2\2\u019b")
        buf.write(u"\u019c\7^\2\2\u019c\u019d\7c\2\2\u019d\u019e\7t\2\2\u019e")
        buf.write(u"\u019f\7e\2\2\u019f\u01a0\7q\2\2\u01a0\u01a1\7v\2\2\u01a1")
        buf.write(u"\u01a2\7j\2\2\u01a2Z\3\2\2\2\u01a3\u01a4\7^\2\2\u01a4")
        buf.write(u"\u01a5\7u\2\2\u01a5\u01a6\7s\2\2\u01a6\u01a7\7t\2\2\u01a7")
        buf.write(u"\u01a8\7v\2\2\u01a8\\\3\2\2\2\u01a9\u01aa\7^\2\2\u01aa")
        buf.write(u"\u01ab\7v\2\2\u01ab\u01ac\7k\2\2\u01ac\u01ad\7o\2\2\u01ad")
        buf.write(u"\u01ae\7g\2\2\u01ae\u01af\7u\2\2\u01af^\3\2\2\2\u01b0")
        buf.write(u"\u01b1\7^\2\2\u01b1\u01b2\7e\2\2\u01b2\u01b3\7f\2\2\u01b3")
        buf.write(u"\u01b4\7q\2\2\u01b4\u01b5\7v\2\2\u01b5`\3\2\2\2\u01b6")
        buf.write(u"\u01b7\7^\2\2\u01b7\u01b8\7f\2\2\u01b8\u01b9\7k\2\2\u01b9")
        buf.write(u"\u01ba\7x\2\2\u01bab\3\2\2\2\u01bb\u01bc\7^\2\2\u01bc")
        buf.write(u"\u01bd\7h\2\2\u01bd\u01be\7t\2\2\u01be\u01bf\7c\2\2\u01bf")
        buf.write(u"\u01c0\7e\2\2\u01c0d\3\2\2\2\u01c1\u01c2\7^\2\2\u01c2")
        buf.write(u"\u01c3\7d\2\2\u01c3\u01c4\7k\2\2\u01c4\u01c5\7p\2\2\u01c5")
        buf.write(u"\u01c6\7q\2\2\u01c6\u01c7\7o\2\2\u01c7f\3\2\2\2\u01c8")
        buf.write(u"\u01c9\7^\2\2\u01c9\u01ca\7f\2\2\u01ca\u01cb\7d\2\2\u01cb")
        buf.write(u"\u01cc\7k\2\2\u01cc\u01cd\7p\2\2\u01cd\u01ce\7q\2\2\u01ce")
        buf.write(u"\u01cf\7o\2\2\u01cfh\3\2\2\2\u01d0\u01d1\7^\2\2\u01d1")
        buf.write(u"\u01d2\7v\2\2\u01d2\u01d3\7d\2\2\u01d3\u01d4\7k\2\2\u01d4")
        buf.write(u"\u01d5\7p\2\2\u01d5\u01d6\7q\2\2\u01d6\u01d7\7o\2\2\u01d7")
        buf.write(u"j\3\2\2\2\u01d8\u01d9\7^\2\2\u01d9\u01da\7o\2\2\u01da")
        buf.write(u"\u01db\7c\2\2\u01db\u01dc\7v\2\2\u01dc\u01dd\7j\2\2\u01dd")
        buf.write(u"\u01de\7k\2\2\u01de\u01df\7v\2\2\u01dfl\3\2\2\2\u01e0")
        buf.write(u"\u01e1\7a\2\2\u01e1n\3\2\2\2\u01e2\u01e3\7`\2\2\u01e3")
        buf.write(u"p\3\2\2\2\u01e4\u01e5\7<\2\2\u01e5r\3\2\2\2\u01e6\u01e7")
        buf.write(u"\t\2\2\2\u01e7t\3\2\2\2\u01e8\u01ec\7f\2\2\u01e9\u01eb")
        buf.write(u"\5s:\2\u01ea\u01e9\3\2\2\2\u01eb\u01ee\3\2\2\2\u01ec")
        buf.write(u"\u01ed\3\2\2\2\u01ec\u01ea\3\2\2\2\u01ed\u01f6\3\2\2")
        buf.write(u"\2\u01ee\u01ec\3\2\2\2\u01ef\u01f7\t\3\2\2\u01f0\u01f2")
        buf.write(u"\7^\2\2\u01f1\u01f3\t\3\2\2\u01f2\u01f1\3\2\2\2\u01f3")
        buf.write(u"\u01f4\3\2\2\2\u01f4\u01f2\3\2\2\2\u01f4\u01f5\3\2\2")
        buf.write(u"\2\u01f5\u01f7\3\2\2\2\u01f6\u01ef\3\2\2\2\u01f6\u01f0")
        buf.write(u"\3\2\2\2\u01f7v\3\2\2\2\u01f8\u01f9\t\3\2\2\u01f9x\3")
        buf.write(u"\2\2\2\u01fa\u01fb\t\4\2\2\u01fbz\3\2\2\2\u01fc\u01fe")
        buf.write(u"\5y=\2\u01fd\u01fc\3\2\2\2\u01fe\u01ff\3\2\2\2\u01ff")
        buf.write(u"\u01fd\3\2\2\2\u01ff\u0200\3\2\2\2\u0200\u0208\3\2\2")
        buf.write(u"\2\u0201\u0202\7.\2\2\u0202\u0203\5y=\2\u0203\u0204\5")
        buf.write(u"y=\2\u0204\u0205\5y=\2\u0205\u0207\3\2\2\2\u0206\u0201")
        buf.write(u"\3\2\2\2\u0207\u020a\3\2\2\2\u0208\u0206\3\2\2\2\u0208")
        buf.write(u"\u0209\3\2\2\2\u0209\u0222\3\2\2\2\u020a\u0208\3\2\2")
        buf.write(u"\2\u020b\u020d\5y=\2\u020c\u020b\3\2\2\2\u020d\u0210")
        buf.write(u"\3\2\2\2\u020e\u020c\3\2\2\2\u020e\u020f\3\2\2\2\u020f")
        buf.write(u"\u0218\3\2\2\2\u0210\u020e\3\2\2\2\u0211\u0212\7.\2\2")
        buf.write(u"\u0212\u0213\5y=\2\u0213\u0214\5y=\2\u0214\u0215\5y=")
        buf.write(u"\2\u0215\u0217\3\2\2\2\u0216\u0211\3\2\2\2\u0217\u021a")
        buf.write(u"\3\2\2\2\u0218\u0216\3\2\2\2\u0218\u0219\3\2\2\2\u0219")
        buf.write(u"\u021b\3\2\2\2\u021a\u0218\3\2\2\2\u021b\u021d\7\60\2")
        buf.write(u"\2\u021c\u021e\5y=\2\u021d\u021c\3\2\2\2\u021e\u021f")
        buf.write(u"\3\2\2\2\u021f\u021d\3\2\2\2\u021f\u0220\3\2\2\2\u0220")
        buf.write(u"\u0222\3\2\2\2\u0221\u01fd\3\2\2\2\u0221\u020e\3\2\2")
        buf.write(u"\2\u0222|\3\2\2\2\u0223\u0224\7?\2\2\u0224~\3\2\2\2\u0225")
        buf.write(u"\u0226\7>\2\2\u0226\u0080\3\2\2\2\u0227\u0228\7^\2\2")
        buf.write(u"\u0228\u0229\7n\2\2\u0229\u022a\7g\2\2\u022a\u022b\7")
        buf.write(u"s\2\2\u022b\u0082\3\2\2\2\u022c\u022d\7@\2\2\u022d\u0084")
        buf.write(u"\3\2\2\2\u022e\u022f\7^\2\2\u022f\u0230\7i\2\2\u0230")
        buf.write(u"\u0231\7g\2\2\u0231\u0232\7s\2\2\u0232\u0086\3\2\2\2")
        buf.write(u"\u0233\u0234\7#\2\2\u0234\u0088\3\2\2\2\u0235\u0237\7")
        buf.write(u"^\2\2\u0236\u0238\t\3\2\2\u0237\u0236\3\2\2\2\u0238\u0239")
        buf.write(u"\3\2\2\2\u0239\u0237\3\2\2\2\u0239\u023a\3\2\2\2\u023a")
        buf.write(u"\u008a\3\2\2\2\17\2\u0090\u00e6\u01ec\u01f4\u01f6\u01ff")
        buf.write(u"\u0208\u020e\u0218\u021f\u0221\u0239\3\b\2\2")
        return buf.getvalue()


class LaTeXLexer(Lexer):

    atn = ATNDeserializer().deserialize(serializedATN())

    decisionsToDFA = [ DFA(ds, i) for i, ds in enumerate(atn.decisionToState) ]

    T__0 = 1
    WS = 2
    ADD = 3
    SUB = 4
    MUL = 5
    DIV = 6
    L_PAREN = 7
    R_PAREN = 8
    L_BRACE = 9
    R_BRACE = 10
    L_BRACKET = 11
    R_BRACKET = 12
    BAR = 13
    FUNC_LIM = 14
    LIM_APPROACH_SYM = 15
    FUNC_INT = 16
    FUNC_SUM = 17
    FUNC_PROD = 18
    FUNC_LOG = 19
    FUNC_LN = 20
    FUNC_SIN = 21
    FUNC_COS = 22
    FUNC_TAN = 23
    FUNC_CSC = 24
    FUNC_SEC = 25
    FUNC_COT = 26
    FUNC_ARCSIN = 27
    FUNC_ARCCOS = 28
    FUNC_ARCTAN = 29
    FUNC_ARCCSC = 30
    FUNC_ARCSEC = 31
    FUNC_ARCCOT = 32
    FUNC_SINH = 33
    FUNC_COSH = 34
    FUNC_TANH = 35
    FUNC_CSCH = 36
    FUNC_SECH = 37
    FUNC_COTH = 38
    FUNC_ARSINH = 39
    FUNC_ARCOSH = 40
    FUNC_ARTANH = 41
    FUNC_ARCSCH = 42
    FUNC_ARSECH = 43
    FUNC_ARCOTH = 44
    FUNC_SQRT = 45
    CMD_TIMES = 46
    CMD_CDOT = 47
    CMD_DIV = 48
    CMD_FRAC = 49
    CMD_BINOM = 50
    CMD_DBINOM = 51
    CMD_TBINOM = 52
    CMD_MATHIT = 53
    UNDERSCORE = 54
    CARET = 55
    COLON = 56
    DIFFERENTIAL = 57
    LETTER = 58
    NUMBER = 59
    EQUAL = 60
    LT = 61
    LTE = 62
    GT = 63
    GTE = 64
    BANG = 65
    SYMBOL = 66

    channelNames = [ u"DEFAULT_TOKEN_CHANNEL", u"HIDDEN" ]

    modeNames = [ u"DEFAULT_MODE" ]

    literalNames = [ u"<INVALID>",
            u"','", u"'+'", u"'-'", u"'*'", u"'/'", u"'('", u"')'", u"'{'",
            u"'}'", u"'['", u"']'", u"'|'", u"'\\lim'", u"'\\int'", u"'\\sum'",
            u"'\\prod'", u"'\\log'", u"'\\ln'", u"'\\sin'", u"'\\cos'",
            u"'\\tan'", u"'\\csc'", u"'\\sec'", u"'\\cot'", u"'\\arcsin'",
            u"'\\arccos'", u"'\\arctan'", u"'\\arccsc'", u"'\\arcsec'",
            u"'\\arccot'", u"'\\sinh'", u"'\\cosh'", u"'\\tanh'", u"'\\csch'",
            u"'\\sech'", u"'\\coth'", u"'\\arsinh'", u"'\\arcosh'", u"'\\artanh'",
            u"'\\arcsch'", u"'\\arsech'", u"'\\arcoth'", u"'\\sqrt'", u"'\\times'",
            u"'\\cdot'", u"'\\div'", u"'\\frac'", u"'\\binom'", u"'\\dbinom'",
            u"'\\tbinom'", u"'\\mathit'", u"'_'", u"'^'", u"':'", u"'='",
            u"'<'", u"'\\leq'", u"'>'", u"'\\geq'", u"'!'" ]

    symbolicNames = [ u"<INVALID>",
            u"WS", u"ADD", u"SUB", u"MUL", u"DIV", u"L_PAREN", u"R_PAREN",
            u"L_BRACE", u"R_BRACE", u"L_BRACKET", u"R_BRACKET", u"BAR",
            u"FUNC_LIM", u"LIM_APPROACH_SYM", u"FUNC_INT", u"FUNC_SUM",
            u"FUNC_PROD", u"FUNC_LOG", u"FUNC_LN", u"FUNC_SIN", u"FUNC_COS",
            u"FUNC_TAN", u"FUNC_CSC", u"FUNC_SEC", u"FUNC_COT", u"FUNC_ARCSIN",
            u"FUNC_ARCCOS", u"FUNC_ARCTAN", u"FUNC_ARCCSC", u"FUNC_ARCSEC",
            u"FUNC_ARCCOT", u"FUNC_SINH", u"FUNC_COSH", u"FUNC_TANH", u"FUNC_CSCH",
            u"FUNC_SECH", u"FUNC_COTH", u"FUNC_ARSINH", u"FUNC_ARCOSH",
            u"FUNC_ARTANH", u"FUNC_ARCSCH", u"FUNC_ARSECH", u"FUNC_ARCOTH",
            u"FUNC_SQRT", u"CMD_TIMES", u"CMD_CDOT", u"CMD_DIV", u"CMD_FRAC",
            u"CMD_BINOM", u"CMD_DBINOM", u"CMD_TBINOM", u"CMD_MATHIT", u"UNDERSCORE",
            u"CARET", u"COLON", u"DIFFERENTIAL", u"LETTER", u"NUMBER", u"EQUAL",
            u"LT", u"LTE", u"GT", u"GTE", u"BANG", u"SYMBOL" ]

    ruleNames = [ u"T__0", u"WS", u"ADD", u"SUB", u"MUL", u"DIV", u"L_PAREN",
                  u"R_PAREN", u"L_BRACE", u"R_BRACE", u"L_BRACKET", u"R_BRACKET",
                  u"BAR", u"FUNC_LIM", u"LIM_APPROACH_SYM", u"FUNC_INT",
                  u"FUNC_SUM", u"FUNC_PROD", u"FUNC_LOG", u"FUNC_LN", u"FUNC_SIN",
                  u"FUNC_COS", u"FUNC_TAN", u"FUNC_CSC", u"FUNC_SEC", u"FUNC_COT",
                  u"FUNC_ARCSIN", u"FUNC_ARCCOS", u"FUNC_ARCTAN", u"FUNC_ARCCSC",
                  u"FUNC_ARCSEC", u"FUNC_ARCCOT", u"FUNC_SINH", u"FUNC_COSH",
                  u"FUNC_TANH", u"FUNC_CSCH", u"FUNC_SECH", u"FUNC_COTH",
                  u"FUNC_ARSINH", u"FUNC_ARCOSH", u"FUNC_ARTANH", u"FUNC_ARCSCH",
                  u"FUNC_ARSECH", u"FUNC_ARCOTH", u"FUNC_SQRT", u"CMD_TIMES",
                  u"CMD_CDOT", u"CMD_DIV", u"CMD_FRAC", u"CMD_BINOM", u"CMD_DBINOM",
                  u"CMD_TBINOM", u"CMD_MATHIT", u"UNDERSCORE", u"CARET",
                  u"COLON", u"WS_CHAR", u"DIFFERENTIAL", u"LETTER", u"DIGIT",
                  u"NUMBER", u"EQUAL", u"LT", u"LTE", u"GT", u"GTE", u"BANG",
                  u"SYMBOL" ]

    grammarFileName = u"LaTeX.g4"

    def __init__(self, input=None, output=sys.stdout):
        super(LaTeXLexer, self).__init__(input, output=output)
        self.checkVersion("4.7.2")
        self._interp = LexerATNSimulator(self, self.atn, self.decisionsToDFA, PredictionContextCache())
        self._actions = None
        self._predicates = None


